# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app navidrome
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      navidrome:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        replicas: 1
        strategy: Recreate
        annotations:
          # reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: deluan/navidrome
              tag: "0.55.2"
            env:
              TZ: ${CLUSTER_TZ}
              ND_LOGLEVEL: info
              ND_REVERSEPROXYWHITELIST: "100.64.0.0/16" # replace with interpolated value
              ND_ENABLEUSEREDITING: false
              ND_BASEURL: "https://music.${SECRET_DOMAIN_INT}"
              ND_PORT: &port 4533
              ND_MUSICFOLDER: /public/Media/Music
              ND_IMAGECACHESIZE: "500MB"
              ND_SCANNER_SCHEDULE: "@every 4h"
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/auth-method: "GET"
          nginx.ingress.kubernetes.io/auth-url: "http://authelia.auth.svc.cluster.local:9091/api/authz/auth-request"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth-k8s.${SECRET_DOMAIN_INT}?rm=$request_method"
          nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/pod-selector: app.kubernetes.io/name=navidrome
          gethomepage.dev/group: Media
          gethomepage.dev/name: Navidrome (K8s)
          gethomepage.dev/icon: navidrome
        enabled: true
        className: internal
        hosts:
          - host: &host music.${SECRET_DOMAIN_INT}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        enabled: true
        size: 2Gi
        storageClass: longhorn-standard
        accessMode: ReadWriteOnce
      public:
        enabled: true
        existingClaim: smb-public-pvc
        type: persistentVolumeClaim
