---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app miniflux
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: miniflux-values
  values:
    controllers:
      miniflux:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/miniflux/miniflux
              tag: 2.2.8
            envFrom:
              - secretRef:
                  name: miniflux-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["/usr/bin/miniflux", "-healthcheck", "auto"]
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8080
    #   app:
    #     serviceName: echo-internal
    #     endpoints:
    #       - port: http
    #         scheme: http
    #         path: /metrics
    #         interval: 1m
    #         scrapeTimeout: 10s
    ingress:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/description: RSS Reader
          gethomepage.dev/widget.type: miniflux
          gethomepage.dev/widget.key: '{{ "{{" }}HOMEPAGE_VAR_MINIFLUX_API_KEY{{ "}}" }}'
          gethomepage.dev/widget.headers.host: rss.${SECRET_DOMAIN_INT}
          gethomepage.dev/widget.url: http://miniflux.default.svc.cluster.local:8080
          gethomepage.dev/icon: miniflux
        className: internal
        hosts:
          # TODO: parameterize this
          - host: &url "rss.${SECRET_DOMAIN_INT}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
