---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: external
  namespace: observability
spec:
  replicaCount: 2
  selectAllByDefault: true
  httpRoute:
    labels:
      auth.xenu.internal/method: sso
    parentRefs:
      - name: envoy-internal
        namespace: network
        sectionName: https
    hostnames:
      - vme.${SECRET_DOMAIN_INT}
  unauthorizedUserAccessSpec:
    targetRefs:
      - crd:
          kind: VMSingle
          name: external
          namespace: observability
