---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: external
  namespace: observability
spec:
  replicaCount: 2
  selectAllByDefault: true
  ingress:
    class_name: internal
    host: vme.${SECRET_DOMAIN_INT}
    annotations:
      nginx.ingress.kubernetes.io/auth-method: "GET"
      nginx.ingress.kubernetes.io/auth-url: "http://authelia.auth.svc.cluster.local:9091/api/authz/auth-request"
      nginx.ingress.kubernetes.io/auth-signin: "https://auth-k8s.${SECRET_DOMAIN_INT}?rm=$request_method"
      nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
  unauthorizedUserAccessSpec:
    targetRefs:
      - crd:
          kind: VMSingle
          name: external
          namespace: observability
