apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    gatus.io/enabled: "true"
  name: victoriametrics-gatus-endpoint
data:
  config.yaml: |
    default-endpoint: &defaults
      group: internal
      interval: 1m
      ui:
        hide-hostname: false
        hide-url: true
      client:
        ignore-redirect: true
      conditions:
        - "[STATUS] == 200"
    endpoints:
      - name: Grafana
        url: "https://grafana-k8s.${SECRET_DOMAIN_INT}/api/health"
        <<: *defaults
      - name: VictoriaMetrics Historical
        url: "https://vme.${SECRET_DOMAIN_INT}/-/healthy"
        <<: *defaults
