apiVersion: v1
kind: Secret
metadata:
  name: victoria-metrics-grafana-secret
stringData:
  admin-user: ENC[AES256_GCM,data:th/U0no=,iv:U9Smf/CdzubUCwQkBrQneW5xjOglBhD/cKBZN507wsU=,tag:oBCuczWZFJQqQvG0nSI4ZA==,type:str]
  admin-password: ENC[AES256_GCM,data:U6aL2kssVrHnfn0LSazkYXIp2Owe0GSnEMHF5+K7fFE=,iv:hBSllXra3DwJcQVnpLuxVlbu6CMcai5emOGabALnt0o=,tag:rp0zmM5Bq0ZGQWmQayCVWA==,type:str]
sops:
  age:
    - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYU82UmZvbmVGVEJhbVlV
        eUFna2F5a3JKOHBnQTJUcnBydTZ4K3htU0g4CjVVVnN2SUJiSzdXbkhqOTNENWhB
        L0NjaTcwRlJSSDMwWmMydWt0ZzR4Q28KLS0tIHdBcklNNkVEbGdzN1NsMkZWTEZN
        OUErY2lhcmJhNUYyQ21DUjF0Z01XaFkK/4yerHA3/OPBFCCtxnQCPWihvKh5qxFD
        cMCHYh1DBFKGy8JUYc/Hqd5DkTjLVbsxMzoqRaWEFrXa5aRZyxlPkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-23T01:52:32Z"
  mac: ENC[AES256_GCM,data:j4+dD579O9Yu0YW3HD3sc8yEafy2gypmzd5ul72RKN/DnE9//2/ldMCSWWEkMZ0OqJVgCIBNJUJcPQP91dQMcpYN+rNfgmQiTVfaLxBZ6B0MTYjosVAOV276drW4xcjQCFbQ2FEWDZbBoLDC9eNO5oG78eozGuDOn6w3/hSY3BQ=,iv:YufybPrkXncpZXt8uXLAn4RV1e4acMh8KFwkgIidphU=,tag:OmH30NH0Jqk8pkpXSWMrMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
