apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana.secret.sops.yaml
  - ./helm/helmrelease.yaml
  - ./external.vmsingle.yaml
  - ./external.vmauth.yaml
  - ./ping-exporter.vmstaticscrape.yaml
  - ./traefik.vmstaticscrape.yaml
configMapGenerator:
  - name: vm-kube-state-metrics-cm
    files:
      - values.yaml=./vm-kube-state-metrics-cm.yaml
configurations:
  - ./helm/kustomizeconfig.yaml
