# Scrape configs for metrics exposed outside of the cluster
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
spec:
  jobName: &jobName "smartctl-external"
  targetEndpoints:
    - targets:
        - "proxmox.${SECRET_DOMAIN_INT}:9633/metrics"
      scrape_interval: 2m
      relabelConfigs:
        - source_labels: [__address__]
          action: replace
          target_label: instance
          regex: "([A-Za-z0-9.-]*).*"
          replacement: $1
metadata:
  name: *jobName
  namespace: observability
