{
 "title": "House",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "INSTANCE",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"home-assistant\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature (Homekit)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "last_over_time({job=\"home-assistant\", __name__=~\"sensor.basement_sensor_air_temperature_value|sensor.*_temperature_2_value\", __name__!~\".*openweathermap.*|.*model_.*\", __name__!=\"sensor.porch_sensor_air_temperature_2_value\", friendly_name !~ \"Flair.*\"}[$__range]) < 212",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "{job=\"home-assistant\", __name__=\"sensor.ecobee_status_homekit_value\"}",
     "legendFormat": "HVAC State"
    }
   ]
  },
  {
   "title": "Outside Conditions",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "last_over_time({job=\"home-assistant\", __name__=\"sensor.porch_sensor_air_temperature_2_value\"}[$__range]) < 212",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "{job=\"home-assistant\", __name__=\"sensor.openweathermap_temperature_value\"}",
     "legendFormat": "Outside Temp"
    },
    {
     "expr": "last_over_time({job=\"home-assistant\", __name__=\"sensor.porch_sensor_humidity_2_value\"}[$__range])",
     "legendFormat": "Outside Humidity"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "last_over_time({job=\"home-assistant\", __name__=~\"sensor.*humidity_value\", __name__!~\".*openweathermap.*\", __name__!=\"sensor.porch_sensor_air_temperature_2_value\"}[$__range])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Water Heater",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "binary_sensor.heat_pump_water_heater_running_value{entity_id=\"heat_pump_water_heater_running\", instance=\"$INSTANCE\"}",
     "legendFormat": "Heat Pump Status"
    },
    {
     "expr": "sum_over_time(binary_sensor.heat_pump_water_heater_running_value{entity_id=\"heat_pump_water_heater_running\", instance=\"$INSTANCE\"}[$__range])",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "Water Heater Total Runtime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(binary_sensor.heat_pump_water_heater_running_value{entity_id=\"heat_pump_water_heater_running\", instance=\"$INSTANCE\"}[$__range])\n",
     "legendFormat": "Heat Pump Status"
    }
   ]
  }
 ]
}