{
 "title": "EdgeRouter",
 "description": "EdgeRouter Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "IFLABEL_eth2", "query": "$${VAR_IFLABEL_ETH2}" },
   { "name": "IFLABEL_eth3", "query": "$${VAR_IFLABEL_ETH3}" },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Link Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "edgerouter_load_balancer_ping_health{instance=\"192.168.1.1\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Current Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=\"eth2\"}[30s]) * 8",
     "legendFormat": "{{ifName}} Rx"
    },
    {
     "expr": "irate(ifHCOutOctets{ifName=\"eth2\"}[30s]) * 8",
     "legendFormat": "{{ifName}} Tx"
    },
    {
     "expr": "irate(ifHCInOctets{ifName=\"eth3\"}[30s]) * 8",
     "legendFormat": "{{ifName}} Rx"
    },
    {
     "expr": "irate(ifHCOutOctets{ifName=\"eth3\"}[30s]) * 8",
     "legendFormat": "{{ifName}} Tx"
    }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ifName)(increase(ifHCInOctets{instance=\"192.168.1.1\", ifName=~\"eth2|eth3\"}[$__range]))",
     "legendFormat": "{{ifName}} Rx"
    },
    {
     "expr": "sum by (ifName)(increase(ifHCOutOctets{instance=\"192.168.1.1\", ifName=~\"eth2|eth3\"}[$__range]))",
     "legendFormat": "{{ifName}} Tx"
    }
   ]
  },
  {
   "title": "Metronet Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{ifName=\"eth2\"}[$__rate_interval]) * 8",
     "legendFormat": "{{ifName}} RX"
    },
    {
     "expr": "rate(ifHCOutOctets{ifName=\"eth2\"}[$__rate_interval]) * 8",
     "legendFormat": "{{ifName}} TX"
    }
   ]
  },
  {
   "title": "T-Mobile Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{ifName=\"eth3\"}[$__rate_interval]) * 8",
     "legendFormat": "{{ifName}} RX"
    },
    {
     "expr": "rate(ifHCOutOctets{ifName=\"eth3\"}[$__rate_interval]) * 8",
     "legendFormat": "{{ifName}} TX"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hrProcessorLoad{job=\"edgerouter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalReal{instance=\"192.168.1.1\"} - memAvailReal{instance=\"192.168.1.1\"}",
     "legendFormat": "Used RAM"
    },
    {
     "expr": "memTotalReal{instance=\"192.168.1.1\"}",
     "legendFormat": "Total RAM"
    }
   ]
  },
  { "title": "Alert History", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 } },
  {
   "title": "WAN Link Weight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "edgerouter_load_balancer_weight_ratio{instance=\"192.168.1.1\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Version History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "group by(version) (edgerouter_info{instance=\"192.168.1.1\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}