{
 "title": "Samba Service",
 "description": "Dashboard for the Samba Server at ${SAMBA_SERVER}",
 "tags": [
  "linux",
  "samba"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "SAMBA_SERVER",
    "label": "Samba Instance",
    "query": {
     "query": "label_values(samba_exporter_information,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Locks per share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "samba_locks_per_share_count{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Locks on  {{share}}"
    }
   ]
  },
  {
   "title": "Samba Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "samba_client_count{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Client Count"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "samba_individual_user_count{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Samba Users "
    }
   ]
  },
  {
   "title": "Samba Resource Usage",
   "type": "timeseries",
   "description": "Samba Resource Usage in percent",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "samba_smbd_sum_cpu_usage_percentage{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "CPU usage in %"
    },
    {
     "expr": "samba_smbd_sum_virtual_memory_usage_percent{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "RAM usage in %"
    }
   ]
  },
  {
   "title": "Samba PIDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "samba_pid_count{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Share PID Count"
    },
    {
     "expr": "samba_smbd_unique_process_id_count{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "smbd PID count"
    }
   ]
  },
  {
   "title": "Used Share Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "samba_share_count{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Used Shares"
    }
   ]
  },
  {
   "title": "Samba Memory Usage",
   "type": "timeseries",
   "description": "RAM usage of all smbd PIDs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "samba_smbd_virtual_memory_usage_bytes{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "PID: {{pid}}"
    },
    {
     "expr": "samba_smbd_sum_virtual_memory_usage_bytes{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "IO Usage",
   "type": "timeseries",
   "description": "Shows the IO usage of the smbd process",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(samba_smbd_sum_io_counter_read_bytes{instance=\"${SAMBA_SERVER}\"} [5m])",
     "legendFormat": "Read Bytes per minute"
    },
    {
     "expr": "rate(samba_smbd_sum_io_counter_write_bytes{instance=\"${SAMBA_SERVER}\"} [5m])",
     "legendFormat": "Write Bytes per minute"
    }
   ]
  },
  {
   "title": "Open files smbd",
   "type": "timeseries",
   "description": "Open files of all smbd process",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "samba_smbd_sum_open_file_count{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Open files"
    }
   ]
  },
  {
   "title": "Protocol Details",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "samba_signing_method_count{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Signing: {{signing}}"
    },
    {
     "expr": "samba_encryption_method_count{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Encryption: {{encryption}}"
    },
    {
     "expr": "samba_protocol_version_count{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Version: {{protocol_version}}"
    }
   ]
  },
  {
   "title": "Client connected since",
   "type": "bargauge",
   "description": "Client connected since",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "samba_client_connected_since_seconds{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "{{client}} "
    }
   ]
  },
  {
   "title": "Lock crated since",
   "type": "bargauge",
   "description": "Lock created since",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "samba_lock_created_since_seconds{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "{{share}} - {{user}} "
    }
   ]
  },
  {
   "title": "Running Versions",
   "type": "state-timeline",
   "description": "Versions of samba and samba_exporter",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "samba_server_information{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "samba Version: {{version}}"
    },
    {
     "expr": "samba_exporter_information{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "samba_exporter Version: {{version}}"
    }
   ]
  },
  {
   "title": "Service States",
   "type": "state-timeline",
   "description": "States of the samba and samba_statusd services",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "samba_server_up{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Samba server up"
    },
    {
     "expr": "samba_satutsd_up{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Samba statusd up"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "samba_request_time{instance=\"${SAMBA_SERVER}\"}",
     "legendFormat": "Request Time"
    }
   ]
  }
 ]
}