{
 "title": "Traefik External",
 "description": "Official dashboard for Standalone Traefik",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "INSTANCE",
    "label": "Instance",
    "query": {
     "query": "label_values(traefik_config_reloads_total,instance)"
    }
   },
   {
    "name": "entrypoint",
    "query": {
     "query": "label_values(traefik_entrypoint_open_connections{instance=\"$INSTANCE\"},entrypoint)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traefik_service_requests_total{instance=\"$INSTANCE\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traefik Instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_config_reloads_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{instance=\"$INSTANCE\", entrypoint=~\"$entrypoint\"}[1m])) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "timeseries",
   "description": "https://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.3\",code=\"200\",entrypoint=~\"$entrypoint\"}[5m])) by (method) + \n sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"1.2\",code=\"200\",entrypoint=~\"$entrypoint\"}[5m])) by (method)) / 2 / \n sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\",entrypoint=~\"$entrypoint\"}[5m])) by (method)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Http Code ",
   "type": "piechart",
   "description": "Mean Distribution",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{instance=\"$INSTANCE\", service=~\"$service.*\",protocol=\"http\"}[1m])) by (method, code)",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Top slow services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        traefik_service_request_duration_seconds_sum{instance=\"$INSTANCE\", service=~\"$service.*\",protocol=\"http\"} / \n          traefik_service_request_duration_seconds_count{instance=\"$INSTANCE\", service=~\"$service.*\",protocol=\"http\"},\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)\n\n",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Most requested services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (service,code) \n          (rate(traefik_service_requests_total{instance=\"$INSTANCE\", service=~\"$service.*\",protocol=\"http\"}[5m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "[{{code}}] on {{service}}"
    }
   ]
  },
  { "title": "HTTP Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "2xx over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (service,method,code) \n          (rate(traefik_service_requests_total{instance=\"$INSTANCE\", service=~\"$service.*\",code=~\"2..\",protocol=\"http\"}[5m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "5xx over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (service,method,code) \n          (rate(traefik_service_requests_total{instance=\"$INSTANCE\", service=~\"$service.*\",code=~\"5..\",protocol=\"http\"}[5m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Other codes over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (service,method,code) \n          (rate(traefik_service_requests_total{instance=\"$INSTANCE\", service=~\"$service.*\",code!~\"2..|5..\",protocol=\"http\"}[5m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (service,method) \n          (rate(traefik_service_requests_bytes_total{instance=\"$INSTANCE\", service=~\"$service.*\",protocol=\"http\"}[1m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{method}} on {{service}}"
    }
   ]
  },
  {
   "title": "Responses Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (service,method) \n          (rate(traefik_service_responses_bytes_total{instance=\"$INSTANCE\", service=~\"$service.*\",protocol=\"http\"}[1m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{method}} on {{service}}"
    }
   ]
  },
  {
   "title": "Connections per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{instance=\"$INSTANCE\", entrypoint=~\"$entrypoint\"}) by (entrypoint)\n",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services failing SLO of 1200ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(\n  1 - (sum by (service)\n    (rate(traefik_service_request_duration_seconds_bucket{le=\"1.2\",service=~\"$service.*\"}[5m])) / sum by (service) \n    (rate(traefik_service_request_duration_seconds_count{instance=\"$INSTANCE\", service=~\"$service.*\"}[5m]))\n  ) > 0,\n  \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"\n)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Services failing SLO of 300ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(\n  1 - (sum by (service)\n    (rate(traefik_service_request_duration_seconds_bucket{le=\"0.3\",service=~\"$service.*\"}[5m])) / sum by (service) \n    (rate(traefik_service_request_duration_seconds_count{service=~\"$service.*\"}[5m]))\n  ) > 0,\n  \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"\n)",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  }
 ]
}