apiVersion: v1
kind: Secret
metadata:
  name: teslamate-secret
  namespace: default
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:kmKIa8HXQjFA62cwk+WIeX2T7dbyVwTbzhRplyyAhns=,iv:3vu4Xk+ruw/nsczV4cqVHLMCIQyewFteimvad0VWfEU=,tag:AFAE3oLUYolWXjmN/UK60A==,type:str]
  MQTT_USERNAME: ENC[AES256_GCM,data:2ps+UO+5Ylas,iv:zMYjxG2lFcMBVaRPpeZjkxaZWY0Owhh/OIh/MSeKF2Q=,tag:puQrVyPkqI+v/zeXVqJUFw==,type:str]
  MQTT_PASSWORD: ENC[AES256_GCM,data:FADaZaIl+cIIP8CKSyxd/ttWoAdSShjHZw0NI3hNh80=,iv:x0u/dWu1BQT+uxswoSqlLIwSiYQZE0KXyod0W9FwBiI=,tag:VFWOA/zTSKOtJuUcYc91VQ==,type:str]
  MQTT_HOST: ENC[AES256_GCM,data:R+RXKYPUrSorc7W8,iv:Ki43cuGtKEToFeJkKoirDYcYeJmz95sh4ftNzYNrC7c=,tag:RAwlB+85R/aJH5BtaNghqw==,type:str]
  DATABASE_SSL: ENC[AES256_GCM,data:OTPrcCsaJGM=,iv:bNmyzsYafDAG9A74FSpZVKxbtwKAjNP6nHPTNxLqwyQ=,tag:7lArG/e25XDjIr7GryLVtg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcW5kcHlrVUd3WWVCS1da
        OXY2dm01aGpySDZnV21UNFlvQ3NOZCtqZHhzCnVSMjg2SmtRYUJOT3lQTEpzOUxN
        M1ZYbXpjb2xzL3hJSS8xS2s4QlNFK3MKLS0tIC9URllSbWlncktvSFM3ekJKWjha
        ZlRGZHp0M0MzbTd3ZEF5UFJncy9kWkEK0fpa3H3gm1+FbDFceA2OEYiDKy4yDhET
        MtImTmYbk6UFLXE9fddKCMH9Tx/iEfr9QPUGdBgwysw6AbODoyJC8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T22:27:11Z"
  mac: ENC[AES256_GCM,data:znq6POKR2l9H+2HJNa5yNROvltP6wmGO8QJr5uJEONy6Sd+9EYhgn91nkOuWNya4D2uqmjir5CoYhWj9nQOUtJb5Q1SvRpLDR+YsGL6SKuexf1PbR7WN9WHNqZ5pMbYcXZo0807zNCMAGoCAvBSMrRt8EFq33gxplCYVhkAgja8=,iv:iZM435uPKfsFG+kfTgvIAY2ImCLVJLiGEnAqTTQqeEM=,tag:r8K/jvA/pKuPfh3H4/STUg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
