# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app navidrome
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/internal
  interval: 1h
  path: ./kubernetes/apps/default/navidrome/app
  postBuild:
    substitute:
      APP: *app
      GATUS_HOST: music
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
      - name: cluster-secrets
        kind: Secret
  dependsOn:
    - name: persistence-smb-volumes
      namespace: default
    - name: longhorn
      namespace: longhorn-system
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
