apiVersion: v1
kind: Secret
metadata:
  name: archivis-secret
stringData:
  ARCHIVIS_ADMIN_USERNAME: ENC[AES256_GCM,data:lIuh9xI=,iv:6KcPPoYsAYrz7hx+UWLpV5aPUtMMeyfTV8YRwIOlGec=,tag:1TOvwbIk/7wzKE3QVB6YXA==,type:str]
  ARCHIVIS_ADMIN_PASSWORD: ENC[AES256_GCM,data:BkR+Al4mW6I5ThPsfGSgAYOZJ4IHfkyxR1TmsHUVGNzjWY70kKo=,iv:M32vNQ6IPksuqpcDV0QQzS7kUqRAVXSdu6A6S/w32CE=,tag:QJNhN+bYgJ++JoljVCCGiA==,type:str]
  ARCHIVIS_ADMIN_EMAIL: ENC[AES256_GCM,data:ZP2ac2b67z6Z9iSxYAC2iQBefg==,iv:c9bs7toaAbZ5o3BzJ2FixoqarzyOWzgFEEU6edCxziE=,tag:4hGs0ixxjHDJLsej2u04Wg==,type:str]
sops:
  age:
    - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd2owSmRGVkRHYUo3eDFR
        Vi9VUjd6VGhmN21ObEgvVGxBVHNaMVVySEFNClJNa2p4TzJGVGg2NVpEcTI1bzh3
        N2hZYlhvaUNZZ2d3UWcva2hCcjlGSTQKLS0tIGhBU0l3aVBHT1pyOXRXbmZXbzl2
        dWlxSUNrWHYrenhGdFFBT2NtZ0daNU0KEoDSoPOWNj3UJC9sJjsqC4mHHHJp8WEu
        ANx0fOVKXkWZGIsZrXFlVXxidsZp3y6WUEFmY5PEVRzyqBjzdi11sQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T02:27:11Z"
  mac: ENC[AES256_GCM,data:w6rGYyoSxVV4sDtyahieK744dqGsCoAJkPEHNratUnaocNfeLT6smrll93RUy6nEWCX8+DZvPbih0xJVsXlRsXdCbdRaEho6MzPwUb5rsd08/6rhvCD1BRAekfLqLP74OOJZYyQPZ1cQyHZYwBbUANS+Qv7qWOb3rA8PHI8Ydh8=,iv:Da4qGz4pICJOeNwztbPFYbb5+5/NTtrj7PYw+xaSsSA=,tag:0ifQlgJbZ2oP5Gt+7J35Ew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
