---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dragonfly-cluster
spec:
  selector:
    matchLabels:
      dragonflydb.io/cluster: dragonfly-shared
  podTargetLabels: ["app"]
  podMetricsEndpoints:
    - port: admin
      interval: 30s
  fallbackScrapeProtocol: PrometheusText1.0.0
