---
autoDirectNodeRoutes: true
bpf:
  masquerade: true
  preAllocateMaps: true
#Enable BPF clock source probing for more efficient tick retrieval.
bpfClockProbe: true
bgpControlPlane:
  enabled: true
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cni:
  # Required for pairing with Multus CNI
  exclusive: false
endpointRoutes:
  enabled: true
envoy:
  enabled: false
dashboards:
  enabled: true
# this requires node/pod bounce
# https://docs.cilium.io/en/latest/operations/performance/tuning/#ipv4-big-tcp
# enableIPv4BIGTCP: true
hubble:
  enabled: false
  # relay:
  #   enabled: true
  # ui:
  #   enabled: true
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: "100.64.0.0/16"
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  # try switching to dsr again from snat
  mode: "dsr"
localRedirectPolicy: true
operator:
  dashboards:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 2
  rollOutPods: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
# no longer needed?
# socketLB:
#   hostNamespaceOnly: true
