---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mumble-server
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      mumble-server:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mumble-voip/mumble-server
              tag: v1.5.735-3
            env:
              TZ: "${CLUSTER_TZ}"
            envFrom:
              - configMapRef:
                  name: mumble-config-cm
              - secretRef:
                  name: pgsql-mumble
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
              limits:
                memory: 128Mi
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "192.168.1.84"
          external-dns.alpha.kubernetes.io/hostname: "mumble.${SECRET_DOMAIN_INT}"
        ports:
          tcp:
            port: 64738
            protocol: TCP
            targetPort: 64738
          udp:
            port: 64738
            protocol: UDP
            targetPort: 64738
