apiVersion: v1
kind: Secret
metadata:
  name: mumble-server-secret
stringData:
  MUMBLE_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:1Wpn33q7QgaN77h3uj2JtfJL8guARSNsf3fopUBVmOCUfV2LrhHeXg==,iv:C34DkAbYHOMvjo/7MZckzIb0KJj7QT+TrlkPGTXuJaI=,tag:xJJGjWlFNLzfND9X3LNkTw==,type:str]
  #ENC[AES256_GCM,data:QiKnJlangw4kUHI8tSS/hOHrNZ+CjMMtALYOjKAN5lQBm0yPAJxNza4a9Zys7X0fVeaGzaIfsENDCqV1ETrKFrgrwL3dsn8E8hhcpISycg==,iv:IRIKHCheBBMAKmwNAA7xOIda8cVZgnB1DTb0ByCRKWk=,tag:imP6u0xJRVXkAkITsReJRA==,type:comment]
  MUMBLE_CONFIG_DBDRIVER: ENC[AES256_GCM,data:swM8aYM=,iv:1lXJ/G616JyyrTAAnlF4nflwv4/+DyfKHuzwfjjdYhs=,tag:N9/9fZNst+N6weFupjzqsA==,type:str]
  #ENC[AES256_GCM,data:w2OLSDaWb13TdjNLkftTcChyfbqXpE4km89o9bm3Bi5fppOmibZbgw==,iv:C6x2yOzVCvTEyieN1S/+4KiP/MHy6/ls5TNN4JsUUNw=,tag:CHxXjDkp1mG5Pcr3Dg+J+A==,type:comment]
  MUMBLE_CONFIG_LOGFILE: ""
  MUMBLE_CONFIG_WELCOMETEXT: ENC[AES256_GCM,data:wX+b13PoK0M+TuoP1dAGZsh5LJolsRpVxrQxpgCe/hZkMszt0BsUvsQQYoITt6+tL20OktHUn4SWL0hKfcATlE6+V6YIM3k=,iv:qBRi3u+taMZmiDFDKclOBb1n4XHVcKDexy5qABQgcRA=,tag:fly67eVBwhQP552X3LMmpw==,type:str]
  MUMBLE_CONFIG_PORT: ENC[AES256_GCM,data:ORGCgBM=,iv:U1x+4bgC/x5F0nXCmoJqE3gzpvjxGhIGSMZg+Ceig4Y=,tag:KxHonkmPaa2GaFvpokVR9Q==,type:str]
  MUMBLE_CONFIG_SERVERPASSWORD: ""
  MUMBLE_CONFIG_BANDWIDTH: ENC[AES256_GCM,data:eNw6zB13,iv:mbz6kK/7g5DR9Ew8XclU7l/svaHCfY9APPj2epu94uQ=,tag:DTZmJY1UFoQ1f+wanf7fHg==,type:str]
  MUMBLE_CONFIG_USERS: ENC[AES256_GCM,data:FcI=,iv:+F4FSn+ZtMKJ6ZMfL9LKQq2WdhambUEDK2pKzlG2Geo=,tag:FGbufPccHOi34elSLWaW/Q==,type:str]
  MUMBLE_CONFIG_MESSAGEBURST: ENC[AES256_GCM,data:eQ==,iv:+TKHzbRMp7BHemnYbpwk+bp/10nTuGyoRuGZODGTDBY=,tag:DJ6p6LkGlo8lZCOkY4N6wg==,type:str]
  MUMBLE_CONFIG_MESSAGELIMIT: ENC[AES256_GCM,data:Tw==,iv:opoTvYI9m8yi8eEYzop+6wZDMSDARuPtwEEKxUlcqLE=,tag:SLLaO7FLRoANxJg152F4Tw==,type:str]
  MUMBLE_CONFIG_ALLOWPING: ENC[AES256_GCM,data:qdgPFQ==,iv:x/mzIY4JJqnBb0C+MSeh7sc4ahtwZD4MqQTKyzyK2s4=,tag:4xtkl2ZWW2ff0viEzcHzHQ==,type:str]
  MUMBLE_CONFIG_CHANNELCOUNTLIMIT: ENC[AES256_GCM,data:lJth,iv:lD3h0/EGmoi0EzpxpB4gyRozMShCIA74XSSKndNmFmA=,tag:YsNHVttktJqTKqkErTEWzg==,type:str]
  MUMBLE_CONFIG_LEGACYPASSWORDHASH: ENC[AES256_GCM,data:bGS2iDQ=,iv:K0mg2SF/ERDM6coEFZr7oFAtyFgUFQCGBo6OAIadXzM=,tag:f2yXsb8/nL1BYEcyiQBqwg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaXcwS0VyYTQ0VEVMVmRr
        L085SDhaclI4bkFXRlFwaDZ2UVhnRzcwQjBnCkcxNHlOdFczL1Z4UVhUL3BzcWFW
        MzJySEY1YnQxcE9xU1liQWtsY1VyaUEKLS0tIEQxK3FGNFlxZ2lKVkhTYWhZdUtM
        Q1crWEwzNS80bjFJQ29XZTJMS0tiaTgKqgcDyO6p561njyZDAADXkc9yPOxYCj4i
        0l8TCxOzxulJbvBMxGFIumllrtQfExBGfsl0H5LfJQdXz4D601govw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-03T20:39:48Z"
  mac: ENC[AES256_GCM,data:j2dSbwWJpzI4jniU05eF9uB7JUQ3fcYVphLSIKMauc6qNraCUtGxmYzwukXWFhnPgUj4xjAiO6kzgMloJmECKZf4/2nMKNJxD3RuNhZauUpEtvN8+BEsjtfT4Hcz0HmKoJiD6cqhnwB3SuyB6raXh7HmJLfjcozbjLedKSL7emI=,iv:Tu9bkE3q0o7rBCSRGvAVN/YCIMWq+nbS+nxwn20Mv1I=,tag:knvg0HuqHPnsmCAvbYzm+Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
