apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: authelia-file-secret
stringData:
  #ENC[AES256_GCM,data:oiLIeHb4MiKATbPxIqfVF+2iRj5ovejw4UrPzqR6HKwmHby7m0AFSYgEws5Wr4lodH9tLVE3SQB9,iv:lh4GETkJY2qBm3TthKNIgmUbYT8fnRcJWq9qA3nQuTk=,tag:YBAF1DfD/SlvUHGn/oF54Q==,type:comment]
  #ENC[AES256_GCM,data:hCW4C25BJCpZ6997QuMoNcXMujOPPJfMZPDhz4MhIElu+ENFAilgqKPlsx6BXx1P0H/KsTbZgUp/KCc48csVRSsjXFxpmBAgDEr55Dkl,iv:DGSr+VQ9JS+aurgf7uSVgOvjOC9leAVKak0/qo6Wob4=,tag:UmuPI/68UbfBEapRVKc8IQ==,type:comment]
  AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:eYFg1yEuOOEG6zm1v/NQzjh1aNod8EJXgi4VmWkCLUxlukTkmVuS9cCxGhO/bL8CWavvRpdO7klWRqip0iuzwg==,iv:Z7tV5v578um1hnSNXttQWLaO8vzkBFFyIDl/Nk1KR7E=,tag:X2aHpaCO4A82zX83Nd/m1w==,type:str]
  AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:wU09OelBIJagxbCyWj4Rtt2LmBtXxJkuO4C345RW7Ct3hDhLG8mx672GHpbX/k0arzVaLOJ2uto0woHlFejagA==,iv:nUa9ZpC5kHc9iYWizaxMkw2uRqepXIIyrc1hH7b8PMo=,tag:bNAjPk+V7LTSeYXp7qzd8w==,type:str]
  AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:LGB9F2wJAzAYIwJRKU8KUq/egen1DomHgtMuGgP5ugQeKe9e7Oq+zPDfRXWzvMMnhdSUttCxkfVxZ9OEDcXy0A==,iv:wi2bQm1WqKsiu/lQR/hKmRz5N0FAXZCT708BAw+uQg8=,tag:RvdEK+inDYkbRqG7kzy8Mw==,type:str]
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:p8uyafsE+U20t3OfkphrwC/4I504MaqNpk87z+Nq/Lz/nwCB3u+/rS+ZPwQ=,iv:WcItpbDvQZGTZ0NCfBaRZkoeK+1SmO6hlaO6Djsm3Do=,tag:+QKZPSL0zz/qiM8noXhiRw==,type:str]
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: ENC[AES256_GCM,data:yKZNO040scD9fsvoxNQUq8PsyQPlSVhROMkJ03BZmpelB+a9FOfDP4nd/iGSE2vQ,iv:CH+S5MwzX5cWdxJF4+BhWlyoWzGBMO7sXEHpkVjV+l8=,tag:eoZgHGrh8xJN9b3hE3B0XA==,type:str]
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERS_FILTER: ENC[AES256_GCM,data:B5F52hHX+J2jK+Tw94w63iXipSkbFMqQLhcqrkcaRPSXd9I8WB376NFgGbcgMuA6WQ4ceQfFLcWP6yERPxr28cWyRUk+hsi/hoMTVVMEpc+HT2BJxtdFUGiw9zZMbUMv0p37KgSxG2adJ/s8Z3LHjIXSVRKgdOm3SNi5XUq0JtrWo+S7uD7a2YTWmBojRm1Yy+a7n79fkGl96/0FBfk7PH4ACYpPbHTpAvP/8qyIJVzZjlp2QSOMS2Wkw0S7A+dhdS7FbQgV5VWPwFh8r3bApBHfCxOgyAXlfcgebSrOzuG7xzbVMLuo4r0YfXgXtFcaD2IlqvDvhDTacO+NCO9o+67SfM4JRPaKYY9LVItRdSgWn183TnYYxzv9/1yT+I9K9uwqayvD,iv:RY+m7Tm5gn5xs9VGu6NMa0CzJgkUg0UznIz86wcv7yo=,tag:ZlC+WZch68X1gYrCACiqhg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cUhxODZaaTJ1Zy81enlD
        M3dSZkdMb3daVjZwWWZadjI1cVZ6QVc3SDBBCkxIUG5rV051QVhZVkJLNGJYMEN5
        SlNBR1V0dWpSRm9OdDU4ZG5ZR0tJcE0KLS0tIHl1Zmoybm83VHpERmw1NDVHZ1lK
        VFBpdElGVm9BRmFqc0NTMXdKNUJ0dVUKXneXXpobN8ho3I9BZaqIIB6sx+vIfjhL
        GQIAqrd0P/HKkC3NAQDwcS0KGwsdmTXdvQB2y7jo9Q5PkJ7tzEoYAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T16:43:16Z"
  mac: ENC[AES256_GCM,data:cRSiqLcxSBWsWwESnSPBvbAEq9UyR2RT4cYXHFAJ7CZVwWTRraooOrbEQxTw2yzhA1smmJQyvA7Tmg5sScDvVyOX23trgHiN9F8meP+PHD/PYBT1d82XlIHMsIrgEDYLu/Kq9II4pTLTS8o/6CBZQpCP/EKFeCrbZxH4Uoi3/bY=,iv:/9olHtysTcud5gYbfkWJt+wVcmmchVJfyoiVFvCowyw=,tag:C6yb0DEtwjsZOS98lOUsPw==,type:str]
  mac_only_encrypted: true
  version: 3.10.1
