---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./file-secret.sops.yaml
configMapGenerator:
  - name: authelia-cm
    files:
      - ./config/authelia-config.yaml
configurations:
  - ./kustomizeconfig.yaml
# generatorOptions:
#   disableNameSuffixHash: true
