---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/main/schema/gateway.networking.k8s.io/referencegrant_v1.json
# Lets Envoy Gateway SecurityPolicies in network use Authelia for external authorization.
apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: authelia-extauthz
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: network
  to:
    - group: ""
      kind: Service
      name: authelia
