---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./mc-common/ks.yaml
  - ./mc-deadly/ks.yaml
  - ./mc-friendly/ks.yaml
  - ./mc-router/ks.yaml
