apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ghcr-login-secret
data:
  .dockerconfigjson: ENC[AES256_GCM,data:UHyV0yBptiNpG2ldCEJgiYNEYTfLoOhf4MNjPvD7I1my2gW10GGFoXB6zDZgu2tnnouFQfONT9ZQpL8x6Fk8CS7NqZ1eG+ngk8rZv2XngDSaObymFLsQzWVK1LDSBpz28pxQasp3zQzFn/JcHFRVo6ekENdSBUYc9tndqpPsuZ/9FmQ6MiIdpQ==,iv:cBh517uEXD9a2jW4P8vcyXJOXaoXODV8ml9Lcxh1NJE=,tag:qs3sMAornP342M9oXvKjhg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWXZUU0R1VFJoVlBsVkYx
        ZTZwaXMzNU9Pd0VCek1XL2Y0ZUpPSytucldrClBKMnBGbmJJcC8yZE5XV0tYdTc2
        bHdwTjk3SnRubzJhRFVWdnhvVVFvSGsKLS0tIERDTWQ5T2VIeDVPZmR0NjNMRTlx
        ZGRCWXJjUmdGN0kzcmpWenF4MlRteEUKPiNj94wmXlLQW56eblnRPd6/7TfP03zi
        Z3XX8tVCKKDmBctg96rEUiNa7aaSbyPZwFTwD9j2qFRwD+N2rQiUng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T00:40:41Z"
  mac: ENC[AES256_GCM,data:pu2onRpKjWhooXpi4o1zelLA2RZ5oxZkWXfGOfYbaPCD0uAC3NeIFgyA8hpO4zLRONwHZup14UvzU/UR4919cNO5wASGnUb7jouge/hScDPxaPi1rjigEQ0l5FviiXrxK30mzKEErQjegWRV29jpEpvpUiZohFPhc6rMBJovhxM=,iv:W44Ms4FX5grwottukFC3oO4oIzfGsRRgQNulzxBrqrg=,tag:nClfUClwa4H2lEz0+J1DNA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
