---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./_persistence/ks.yaml
  - ./echo/ks.yaml
  - ./echo-internal/ks.yaml
  - ./miniflux/ks.yaml
  - ./homepage/ks.yaml
  - ./spoolman/ks.yaml
  - ./teslamate/ks.yaml
  - ./mumble-server/ks.yaml
  - ./navidrome/ks.yaml
  - ./calibre-web-automated/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
