---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
components:
  - ../../components/common
resources:
  - ./coredns-resolver/ks.yaml
  - ./external-proxy/ks.yaml
