---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/main/schema/gateway.networking.k8s.io/referencegrant_v1.json
# Lets SecurityPolicies in network select HTTPRoutes in this namespace by label.
apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: network-securitypolicies
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: network
  to:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
