# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JXBI43EiybAYhmuhor0UQ7isMtOFnpjW1RK40NsGbXOQTBqyuOckHQ==,iv:vfkxtb2nGxK/GW1E9jvHTbTjlJl1EYOfgLfmtP19oRA=,tag:mLftwUs0x/IL+3ZX/hpQUg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MDNScThwUjJNUFVPRTdD
        b0FVME84MG9ERUU3RURacCtLNHg4akdUb3pVCmF3Wk5OWXI2cTFNNHUwWkZyYVhM
        eTZJQXlCc1pqNlhpKzNHemdPK0lMa0EKLS0tIGp4QXJOUWp3YlhQTVdwMHB4NXEy
        WDYyMlZnRVVvQlp3NmJ2YlZBMXpob2cKNy1RpCeDyZNeTGVmyx7MVgPn4p1QpoWh
        GKHDkZzAi3iUEjrIMHI3jRxUFeW+RvLuLWit8RzER6XReRj1g6aYRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T18:47:01Z"
  mac: ENC[AES256_GCM,data:yZQA33Jvz0P0099B+9Yil4fReoGcOk56p+2GNvDrB/STOVymKH94olQ8cb7iuE92jrLn4rZKV/nqpX1wsEALit77JZyoVgg0SvdDAaJej/+D+XfMhbAcA5VBHCH0mjkJd/hdMKLz3FIyYPS2tUWO3zaWadA+E8GE22LWEqiSVlU=,iv:ARYAa7A/sbHtFfqGaovv7CNz1SHPwgrmZaB5TXX/5eg=,tag:wG8TQQ5/b710WieBMe9bPQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
