---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/persistentvolume.json
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: smb-public-pv
spec:
  capacity:
    storage: 2T
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    # permissions are handled server-side
    - noperm
  csi:
    driver: smb.csi.k8s.io
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: blackhole2.${SECRET_DOMAIN_INT}/public
    volumeAttributes:
      source: //blackhole2.${SECRET_DOMAIN_INT}/public
    nodeStageSecretRef:
      name: smb-appdownloader-secret
      namespace: kube-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/persistentvolumeclaim.json
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smb-public-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2T
  volumeName: smb-public-pv
  storageClassName: smb
