apiVersion: v1
kind: Secret
metadata:
    name: mc-deadly-secret
stringData:
    OPS: ENC[AES256_GCM,data:2QG+rZ3zLTME6A==,iv:JxQ84hQhRJcokBhVr1lYevEMgsJMOrY5IMmvPQLqlfQ=,tag:UK4nkNS79JH/taV1yEz9FQ==,type:str]
    RCON_PASSWORD: ENC[AES256_GCM,data:9B2Vj3LYKKQGR58arppY,iv:dvum7ZO+6umKd/pXdQMXpKgslgUn1IMMLni81qj1BOo=,tag:KuIEofqk3+Q+oshmpSv4yg==,type:str]
    MOTD: ENC[AES256_GCM,data:sVughg3g1VrirgOvDZea7krB5v6AqeTuaeuFUztiqJjjatM79SW4bQX3,iv:0g6THtBmYs/6Q8zXTeuXlXKhtEkXYGkyLn0bN1+mUNs=,tag:ca4Y/BVoO3eSX4XgH0M/MA==,type:str]
sops:
    age:
        - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa05FRElQMlVTMXNFSXNt
            NXp1Q0MwdnBlOFhYeUpYSzhsRFQ4cG5rd3hBCmdhRGtRMXRLTVhVcWpyVDBFVXBv
            b1hwUFNJK2EzdlFhY2Vaa3kvZE1nNlkKLS0tIDJwaGxrT24wTGsvVENqTmpYcWFY
            UTNGNnlSWkVScGlJUHlyQ3o0YU8xREEK11Sv8GQrH1M9bFCnD4p5ccH0nSje1DQB
            NsfHEuZUHXSPmEcjwkPgiirMHXWTkwkVinbCEYPaDFMkusTiSAYKOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T02:08:36Z"
    mac: ENC[AES256_GCM,data:XQzI2dWZs+Ktd0UC5ucNUmH13dA67Q57UudNYzzGG+QmjgMQL7x/7OVKQ+lyfPopEGW5xrTKhhXtpde0wC5+WgC6oUi0iRN3s2c1z3whqWEM41ytRYTmKpwpppcX43u5dtCgO/qyS1AXsncdtOm2E0TmK8gMfFrzsDbpiUE2+ok=,iv:1ObcAwrHkArdTXrF8hGDKnVorLtBBsiqF9CNpDc3gEs=,tag:UQ5eJt/nfhvjN3tijE5MGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
