apiVersion: v1
kind: Secret
metadata:
  name: isponsorblocktv-secret
stringData:
  config.json: ENC[AES256_GCM,data:TTdQSWZjSlJj5N/YncmC2UXV6JkYeqa+sO99ae078h0CelwEEwykaUs2Tm210rQud4y7aa+B+GXeJvHdIyFRjnELmr/KuOKUPl87AQdPKQRv2Jq1Mqc2PnulaXQJ+Q89HH0WZbb1kKSIVD499bPhgPybc1Otm+MYYp6Z/xw+tZ4Y8VOlLnnHXaImOsDfz+uP0UysAl67AXkon+bs2x86Fdh3zkT+euGNMelv1SFXvfbm/0xGuCAVrx3/2+of0bLyi2lp+VyvhuC3ZbvmYZBBSqInBkZRMnZXvipau9k+fdrxzO9VY0nxHzhNCgcGljRWYhEHzoSB9qB4iLb2wI8pIlMPrHLct1Jw6NdA10LlKfTzGH83WkZfGtiZsbRj6EmSffCHxoyoU+2c4j5qBACE4Xm0eF8oZ+eVxTu+ZTd6bkUK71JjGOzosH1cQY5g1qAKmUN5mqFqsnCYEa2xxPGjh/rPqp4ruLwpNDqw2f5rr/rtwudhsMsI99vLtdFi8lGZzzBTae3MhAXE8RK7yN+9Of23FqYswUxIVK+p0D8Al5f5vHf5VYV5VO2m1JbZ5GkICwDQyEp/TPL3uqyg++2APaTOPFWjEVIUuJZ35DoSS6eiqZOU0yCZPrMdtxWSrX+H3SombpYubwiXxiy6mCanKaXthBeFD0ZLgOsiPO87fHfJHcYh6Pb5WZYU/+TSoELqo2HFjpL2+8bHesBFcpXpnF4OmbkhFfv6TLNVOZroiuuLHV9sueUXg+D+tWa3SIDwzVrtjbGQS9woo3ZUcJGmiLHWR0dtJ4VNUyXUqZgh/TuGiGavVTJv1l+J,iv:VTxJ/QxXuhXGYe4oaMYEM7Y8LrcaWlVXOFelKp3d7SA=,tag:qZ22rGEzpRwyoTj+tQXH4g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMVc1bXNXdWcrSDd5SHlO
        WVJUZVVDQU9JSVlpV2NOUEkvRUsxT1lYTmdFClUzZStHU01ZUFkwWTNNNWdHSEgw
        NnhSalNaL0RIWWhUVGQ2ZnBGaHllTU0KLS0tIGJmdnRnZjVkQnFQdHZNMjQ2ekhF
        MHI4UzVOQlVMTE5oWGRDVXdqNllMRUUKlgbg7bjxrd+wxEG09Xat/oIi06kntuJ8
        Hby2/eLaXkZeM1tlx8zqP6v9Eb+oTwvRDx5itvxqT/HQ8NpE5qT1xQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T01:00:42Z"
  mac: ENC[AES256_GCM,data:C2AzkHiXJ1J8YbYX959U7lo8aGa2iyeYTAFCnKfnmaJ9JSEaqDc+XZT6B+ekcmziwKlksn6xjrnnTDAbJgon7knzokjR5M+Rg4pRuF2H/vZPhZ1BnYUca+wojwN6fQKA2kRg8tlXbMrZwSICN2vLG8f5k3oN293D6xIjFCi/c70=,iv:35bpHTY+B6luaJnRLNFoeFINFQmdJ2sG82XGW2jLO8A=,tag:MK+XAKelV2c2KzmuEmTvOg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
