apiVersion: v1
kind: Secret
metadata:
  name: booklore-secret
stringData:
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:uIL40mUKgjcqcmUdWqyqglFZTBUAjWwwtBXcQVk=,iv:CMpj7Me9tAKRRtwpWji9xFWUdjyZfvWMrcD1v4Kwt8s=,tag:hujpfvN5JMQfOAAJ3Ljzbg==,type:str]
  MYSQL_DATABASE: ENC[AES256_GCM,data:oUZmhaoJ0t4=,iv:8IcEoWcwrUHyJqCtv2odIkpPTXYQJJ1udPJOTunpP4g=,tag:gJtd94VAQYX/5xWuSWsPvQ==,type:str]
  MYSQL_USER: ENC[AES256_GCM,data:h5kQfnWN0hs=,iv:revr3dtNNgaBLvDX+R2p2LtpScAhprGZE3ohun7ZNIY=,tag:nkBbZLBnuuISHymbwCzFjQ==,type:str]
  MYSQL_PASSWORD: ENC[AES256_GCM,data:SSXDcOLoyrUxdKNJF6SKNG6vCvs9LKqz,iv:WXGHvBT0zArxAckINyioJJdVxESLKZ5iHNXe1/jFofU=,tag:rzM2Xz3RXxMVK+VDrcFRmQ==,type:str]
  REMOTE_AUTH_ADMIN_GROUP: ENC[AES256_GCM,data:eiwAFhqfhJ4F,iv:KimTvW7gE8YMLLpfmNhF+2kZyMNfDxCG+Lio8HNjg88=,tag:MvZlEeBh2CpZxV6mUUPJog==,type:str]
sops:
  age:
    - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOGd4eEFZRTcrdmMzMnZK
        SUIyNXRnc0k5eW1iR1M5dTg1UElRNGlYVHk4CjJFQlBVcUJWYkZ2aFNqdFV5VHhI
        RVJXNmw0cW8waFBFYkNPNkswQ0FsRE0KLS0tIE41VzF3cmMzMHBQcU9qSDM5Ky81
        c0k5MTdQM3RCbzgrVHhMa0pjSFYyeWcKa2D9HNnOQ1B3MMAHkDs71DDTZgjbmpKg
        tVKfsbIrqEHdrZCBkTmqhMjMuP+UL7jiJ2hHW0kOECb/kpCxPVY7qA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T22:28:35Z"
  mac: ENC[AES256_GCM,data:BsSquYwGiS/BF3XE+za3ziSYgzfZsGKgDr8U34VxaBhlwbNEl4HrGhPGN5VMz+eRSBPgbsgAwa5IUvlthmw8kLwyHaAGLW0H+ZR6SAxY7w3qyV6jOvBCSLq4BjQE03otMdmTVaOOjGtxyywZ51oFWKpiitwzCTc5otnRBXeePUE=,iv:xE5T5/o4s0QOI2/LSpOOYXheYyX8zaQ1o4PZTfqWxWM=,tag:WBBZjvXahRY+kcOtXfVJfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
