---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./victoria-metrics/ks.yaml
  - ./grafana-dashboards/kustomization.yaml
  - ./smartctl-exporter/ks.yaml
  - ./prometheus-pve-exporter/ks.yaml
  - ./snmp-exporter/ks.yaml
  - ./unpoller/ks.yaml
