---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db
components:
  - ../../components/common
resources:
  - ./cloudnative-pg/ks.yaml
  - ./ext-postgres-operator/ks.yaml
  - ./dragonfly/ks.yaml
