apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5.conf
data:
  krb5.conf: ENC[AES256_GCM,data:qffF6HD2krRE2baMuiX0yUW1dF6x8jJZKBhI+Rd/8mm5MB5c3MXlWdBrXmevOZ9Ln0v3noVHPZ+WUrAlOLuvsUsX6gBnRANALAANHf3FNxHCrZeKsjzUMbnJkn4b2j8iHPr0X9a0QJBBYQ21BKVl41jUDOTdyOX9TI4VM7HiJz2Tw3/TrUruMH2DPcrD1t0Fr4U1pNGhuv0lxTvVEwfAKn96BR7g4ok6yeMfUsVk/9uW7+fMvPh7PHZPrCzp4V6jPGakiodqXDRGqvCJ6gAKkJFU9aa0DgeCORe+vdsoxZk3iANDG/qmRzj0ymhwdhWW/ktMYoaK9wY0zHGFMZ1BBOK3lZydMqEwDcsK/qrNK1Y9tkL45fQBPy47DvvwCHzyvUD8byrrVx5eNCCf5tHdzIr1I838psP/H6yjIW41W3mfVZw7VpJR7O2mfjBshUpHfdQJ4cl/Yo9m9ZMpyIgkqSqpgRPmoQ3lTeHOsSV95wQgAipF0uess93GuuvPOF+LLTqhe87d/X9pf6yjZr0fhHZpxgx7nsghGwUc1wJaTSfxiRMdNLjGgQW0A5rCSA0LBDbPCl3Z1HbSVT5mbIlGiCJyGuxaUKR9HyR7U7U5PlpZ9ZiZhnY6zfEm8Jd4UFrXelzwDpiYu3beqyAhG7Mk0U6UeKRdcfgmXlt2/7kd4zvU70ElgoIyt33QiQPwuowpHJnRq5+c9Z/FD1OCJX1Q4AJgnJvE5nqDpHYPxCGklejYE5MElb0GcEQFIR4SonuwW4x4OPaypoj7ItaeXRWHfKKMX3QjR48RISRcnFJQ1F1T1A0zB+1u1IixIQzM/X2FHAo01kEl2IKQBTTh0EJKBuru8WVzkUgx81pLyw==,iv:SYIjXJKPxhOoy2SKhGMrlGxCQfcYo8tnFtIRZE0a/p4=,tag:JbDdMT7y4pPu0qVqiNwMRA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWjVwS0lOTy81S1dMZkNs
        SWlOZ2hkZEVERUplNXV6QklVazhUdDZWY2k0CmwwdS82U2JPaTloaGVaTXdCRDcw
        LzRpcmNqTktkbmNBWUlwZmVFbFF6MGsKLS0tIHJ2dmNlMi9QSUxjdlRsdGlxcmZI
        U1plZllBZVJWaTFEUWZubnlwN0tyRTgKYsRUJEIKdP6PaANmY0+BLPAjoyHQeRk1
        Y5lFO5/rwJAAOql7iLHR2KA+uAYOu0u0VXXkH+3KmwkCDhM2whVVYw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T01:17:01Z"
  mac: ENC[AES256_GCM,data:H7WL1q8A1KgPwVaTD+wt8fqpHLAE4/SYkCWvlQcxQDfR+SzsPquB72CH5hClh8nlSqUMVW6dTX9ZabbYGm+k1zA/1Fwc0H3tHuOTGf7fd+tSGLf12POhZ8wkLL9O9dp9Sp4YfLFxwcVZnnDAbYtZytCn8/5WLoh8Nn0EHH4BfZA=,iv:wlaQSMkE/WNibzoEaKjhOcSgTZ3DVecxFAj5DpCnxlU=,tag:6UNofXI8xCv68CCP8GwPjg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
