---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/main/schema/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app teslamate
  namespace: &namespace default
spec:
  dependsOn:
    - name: teslamate-db
      namespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/internal
  interval: 1h
  path: ./kubernetes/apps/default/teslamate/app
  postBuild:
    substitute:
      APP: *app
      GATUS_PATH: "/health_check"
      # Image tag and Grafana dashboard release
      # renovate: datasource=docker depName=teslamate/teslamate
      TESLAMATE_VERSION: 4.3.0
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 2m
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/main/schema/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app teslamate-db
  namespace: default
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: db
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      failed: &failed >-
        has(status.applied) && !status.applied &&
        has(status.observedGeneration) && status.observedGeneration == metadata.generation
      current: &current >-
        has(status.applied) && status.applied &&
        has(status.observedGeneration) && status.observedGeneration == metadata.generation
    - apiVersion: postgresql.cnpg.io/v1
      kind: DatabaseRole
      failed: *failed
      current: *current
    - apiVersion: grafana.integreatly.org/v1beta1
      kind: GrafanaDatasource
      failed: >-
        has(status.conditions) && status.conditions.exists(e, e.type == 'DatasourceSynchronized' &&
        e.status == 'False' && e.observedGeneration == metadata.generation)
      current: >-
        has(status.conditions) && status.conditions.exists(e, e.type == 'DatasourceSynchronized' &&
        e.status == 'True' && e.observedGeneration == metadata.generation)
  interval: 30m
  path: ./kubernetes/apps/default/teslamate/db
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: db
  timeout: 5m
  wait: true
