---
# yaml-language-server: $schema=https://crd.movishell.pl/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: prometheus-smartctl-exporter
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.14.0
  url: oci://ghcr.io/prometheus-community/charts/prometheus-smartctl-exporter
---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: prometheus-smartctl-exporter
  interval: 1h
  maxHistory: 3
  upgrade:
    remediation:
      retries: -1
  uninstall:
    keepHistory: false
  values:
    config:
      # temporary value for VMs, this will be nvme on bare metal
      device_include: "sd.*"
    fullnameOverride: *app
    serviceMonitor:
      enabled: true
      serviceName: *app
      endpoints:
        - port: http
          scheme: http
          path: /metrics
          interval: 1m
          scrapeTimeout: 10s
      relabelings:
        - action: labeldrop
          regex: (pod)
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_node_name # Use the node name where the pod is running
          targetLabel: instance
    prometheusRules:
      enabled: false
