---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snmp-exporter
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 9.6.2
  url: oci://ghcr.io/prometheus-community/charts/prometheus-snmp-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: snmp-exporter
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: snmp-exporter-modules
      valuesKey: modules.yaml
  values:
    replicas: 0
    podAnnotations:
      reloader.stakater.com/auto: "true"
    fullnameOverride: *app
    serviceMonitor:
      enabled: true
      params:
        - name: edgerouter
          module: ["edgerouter"]
          target: 192.168.1.1
          auth: ["public_v2"]
      path: /snmp
      scrapeTimeout: 5s
      scrapeInterval: 15s
      relabelings:
        - action: replace
          sourceLabels:
            - __param_target
          targetLabel: instance
