---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emberstack-charts
spec:
  interval: 1h
  url: https://emberstack.github.io/helm-charts
  timeout: 3m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app reflector
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: reflector
      version: 9.0.342
      sourceRef:
        kind: HelmRepository
        name: emberstack-charts
      interval: 10m
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  values:
    fullnameOverride: reflector
