apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud-secret
stringData:
    GRAFANA_CLOUD_LOKI_URL: ENC[AES256_GCM,data:T+bQ0gIVi2nADYC0TVQ/2Yc135ohvXWsd3/rsHTeyy6woYfa6XIvqOueIQPWVFPR,iv:pX7qimi09YrkiCQIFhqrLVomEmoyP7GFmBKujhFE3mw=,tag:RFNeVUX7GiyiUAq9JhtV2A==,type:str]
    GRAFANA_CLOUD_LOKI_USERNAME: ENC[AES256_GCM,data:R3ZDwZfk,iv:FXF6VbGp5yHl1JRfjgqUCnPldBQphr6s0YITz5HVw3Y=,tag:kjEX6jOJfPVIGGGOdOt34Q==,type:str]
    GRAFANA_CLOUD_LOKI_PASSWORD: ENC[AES256_GCM,data:JYOmDFOG1qzQptSSP+7JAfzhkZJkpIo09hgnbiyYa8yTG3oDCZYw7fAZFdzcOIUL7tyWVQQDtf9I4j2xJpjBYt24xUQsEExJXTBsTp01QZcB6XiG/D/BHf/AHqnkp/Ml1/HTUdYvgTgpPxCDfFAKDZLJmp/hVAYNWC99vNzfwEo1SkcWOIl3BQ==,iv:QcHUTBo7Sphh/r8g/2CqxQ0Ist1WVdPjZo0EOPH5rKg=,tag:4/UP3KoLN+cMF9mw1/rGNw==,type:str]
sops:
    age:
        - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsajlhb3BqRWVMeStyQ2pJ
            cjhQZ2pzR0JYZHZmR3hMYTZEV1h0eGhwdVMwCjhSV2JDVUJGaWVLS0o3cjZyZzBN
            N3JaZXdubnFSMUY0eXhPN25jMjdvMWMKLS0tIGV0UkNrY0J4Y1JpcnM5WWVSZ0hk
            R3Fydmw2KzRzYmI4Y284VWQxRmN3Y1EKPF/VLGY/5cYeMdrYQyRwZJVUNW5IywwH
            wKOt0e2ODo3gMkG9ZVVWBBD/066X6/3qKK9RmpIsy1VtTNpE9+rUjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T01:58:34Z"
    mac: ENC[AES256_GCM,data:pcBolsA5cx14Pfw8XXXsJaAhQIp2jNP9Ld16fbs2YVKqAijMZ2wvS8e1RVng5WHsnAElkcG2HBW0gkhO1aN6fQD4sz7WFEykPfDBKe+pe/FKiU0FRhugjIKUPAnmCHZwrvlEDS4cri1ct9dztj2Tkh82B6ePOB/eopH7khghs10=,iv:E0ONxtieuDX5WalfNYU4TEKa4D1rGXIrIJ0xSdB9Ytw=,tag:QtNansZJ6cZAx0bVGbp+Rg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
