apiVersion: v1
kind: Secret
metadata:
  name: grafana-loki-datasource
  labels:
    grafana_datasource: "1"
stringData:
  loki.yaml: ENC[AES256_GCM,data:Z3Tb+T539B0304f8isw/quY9feUygCziMz3fWAgtKIjQ+6W42k3HstM11onNEWnC8AuYRyRI7HGrzKIG9ac8VT65k1ojpqlTICm/CWKGNDZK/1/vd8wG21mYum+WsHr4wt5FqBskx1Z+Dp076g5DgaHG8q5sxD7sc16Q9najucCdf+c4THnyt0Ugi8g3SzzICFggpvAwHmFmUF2qiXA9aVKSqdaHbJwZGI3pYJqvFB98RHtH19BGXpJNTBLgTaYOLnSXXYHFyE8w3SiixkgwOqjW973caJm9hYTIDUFVZAc9MKz4iALa8200iKFDAik06MzZY7X8mP207sRmBUmoqu5MnkfajrT95ils620B4gcF/5dDsHnLKKdXCZn14OmTef7qoMFyb8oUZbJ3v4wG+J1FsvU2MKhYjp32kSmOIYPrEMTaq64l/nyR3p1LRZzGCCvwqHlRiYcyd4yLzi4zQuRNGLrSZGGRVvs+pn8NQKmUJZ6sEj5RJjqgbUVxPbOS7s4=,iv:yE4AiZ2mlNQbCyMoPJb0SZCAXrH1Ld8UkaVFKGks6aM=,tag:d1bLPR+eCTjCNnMRUXFw7Q==,type:str]
sops:
  age:
    - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSE9LeXJldFhoNzFzbjlY
        RmMyYk9zYXVVTjlCVi9IQUphL3liRHZaa1hzClRVeFB2MWcyQkdQMDNuNE5RS1lH
        eU1LUDYyc2Z1RGYzOXNONkFiclNCaTgKLS0tIG9nVU1yWUtXTXF4S2ovVmxJeTRI
        Zlp1MksvNUc5emxGT1JDcmhSSEhtdk0KR1j1hDN6XcmsfmB2XydjSIK3kSsJLlcO
        NhS7NlD+6qwiEvh9/bXbRCzIHYT8/VRWW1QWte3U7PtZyoEVFADRQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-12T02:08:44Z"
  mac: ENC[AES256_GCM,data:1nS8PxE4mNtnW7mS4w2LPUPJfQfwXnZEBm1bj2AoaguZyPxmtUOsz6ouLkctchlIhOR4EAA1LT+AQKW4P7G644QW7ePqpPbbc8f9xt5ErT6FgA5EI+5++iSQWqH1dCbQheT4Cbz33H1uB+VXMREAxv0hdaQ+Qy0UpLGqqdyg03I=,iv:PYtfmKytHhSXSDkP2LzJWAgUoSo04UJeUzuC71W3CP4=,tag:Ke+gFlAZxRMhHG2sm3Yqfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
