---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepo.yaml
  - ./helmrelease.yaml
  - ../resources/storageclasses.yaml
  - ../resources/cifs.secret.sops.yaml
  - ../resources/garage.secret.sops.yaml
