---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/main/schema/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app spoolman
  namespace: &namespace default
spec:
  dependsOn:
    - name: spoolman-db
      namespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/internal
  interval: 1h
  path: ./kubernetes/apps/default/spoolman/app
  postBuild:
    substitute:
      APP: *app
      GATUS_PATH: "/api/v1/health"
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 2m
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/main/schema/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app spoolman-db
  namespace: default
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: db
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      failed: &failed >-
        has(status.applied) && !status.applied &&
        has(status.observedGeneration) && status.observedGeneration == metadata.generation
      current: &current >-
        has(status.applied) && status.applied &&
        has(status.observedGeneration) && status.observedGeneration == metadata.generation
    - apiVersion: postgresql.cnpg.io/v1
      kind: DatabaseRole
      failed: *failed
      current: *current
  interval: 30m
  path: ./kubernetes/apps/default/spoolman/db
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: db
  timeout: 5m
  wait: true
