apiVersion: v1
kind: Secret
metadata:
    name: longhorn-cifs-secret
    namespace: longhorn-system
type: Opaque
stringData:
    CIFS_USERNAME: ENC[AES256_GCM,data:0CisMkPQn1v+DDfVkP2QpzP9wgA0EBgJzO9+F48b,iv:FjuJZVjeNCD9VEiMr7T5sd+k/wuxjQ5ALlSFluhvqFw=,tag:T8Qt4R5ukumWxTPX5b6hnw==,type:str]
    CIFS_PASSWORD: ENC[AES256_GCM,data:YHpaxsLNcmEZNP/22ZURtDFOXaVwlV9gMhL7YAXZpE8=,iv:Jr6MZHYhV9iMPeiX3QVroJtOY+zOdE/oN92tuwt+m4c=,tag:3DKf0J2NPTy42qwlLxkV0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbmgxNlJsc2dZV25rWU5X
            eXVoUFBNVEUyQU9nVGpXbEp3K0R0b2lmaENvCm8ranNWYzhEYmlLekdEYS9OczFS
            UUhmaDg4QmNDTHVjU25EeDdWT21VQmcKLS0tIHNoOFlsU0FYS3VJcEZDQlcvYWZw
            NjA5d1J1QnJRR3JibzVUSUdrVm5RSmMKUvghYvPKq3O66dBTzPyvoLpd37N1WS6M
            xwMathTiMbJANgCIlePsuZ0hwrkoISqsKENCSaTvDrHTxGJXzHazBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T20:31:45Z"
    mac: ENC[AES256_GCM,data:7ydlVlOdDRdUd7UOmcrvDgWhey5I5/AFRjy2LNyxpkHlRGSD53Zuv7IdjC0L1t1Hb6XA9WdeI6YVjSUo5f1H0x5Or5gF8gai6p50En1sUYA3KvihRY206LwUsdhoW82FuYCeSHIo9k65prOS6aNch9/iq2YmKsSIdvTheGzNVlM=,iv:sAlcThDnIvhCI187P8Qrkcz3Gh0O8G+a+HjWlQwGAzY=,tag:toNJ7wAsBbljuwQhZhRKvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
