---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "240"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  backupTargetName: "garage"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-immediate
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "240"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  backupTargetName: "garage"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-cluster
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  fromBackup: ""
  fsType: "ext4"
  # strict-local was causing issues with workload migration, requiring manual intervention
  # using best-effort until Longhorn improves eviction handling
  dataLocality: "best-effort"
  backupTargetName: "garage"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-yolo
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  backupTargetName: "garage"
